# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# -- Reference to one or more secrets essential for pulling container images.
imagePullSecrets: []

# -- The number of Operator replicas.
replicaCount: 2

# Operator-global options.
operator:
  image:
    # -- Image repository.
    repository: hashicorp/terraform-cloud-operator
    # -- Image pull policy.
    pullPolicy: IfNotPresent
    # -- Image tag. Defaults to `.Chart.AppVersion`.
    tag: ""
  resources:
    limits:
      # -- Limits as a maximum amount of CPU to be used by a container.
      cpu: 500m
      # -- Limits as a maximum amount of memory to be used by a container.
      memory: 128Mi
    requests:
      # -- Guaranteed minimum amount of CPU to be used by a container.
      cpu: 50m
      # -- Guaranteed minimum amount of memory to be used by a container.
      memory: 64Mi

  # -- The minimum frequency at which watched resources are reconciled. Format: `5s`, `1m`, etc.
  syncPeriod: 5m

  # -- List of namespaces the controllers should watch.
  watchedNamespaces: []

  # -- The API URL of a Terraform Enterprise instance.
  tfeAddress: ""

  # -- Whether or not to ignore TLS certification warnings.
  skipTLSVerify: false

kubeRbacProxy:
  image:
    # -- Image repository.
    repository: quay.io/brancz/kube-rbac-proxy
    # -- Image pull policy.
    pullPolicy: IfNotPresent
    # -- Image tag.
    tag: v0.18.0

  resources:
    limits:
      # -- Limits as a maximum amount of CPU to be used by a container.
      cpu: 500m
      # -- Limits as a maximum amount of memory to be used by a container.
      memory: 128Mi
    requests:
      # -- Guaranteed minimum amount of CPU to be used by a container.
      cpu: 50m
      # -- Guaranteed minimum amount of memory to be used by a container.
      memory: 64Mi

# Controllers-specific options.
controllers:
  agentPool:
    # --  The number of the Agent Pool controller workers.
    workers: 1
  module:
    # -- The number of the Module controller workers.
    workers: 1
  project:
    # -- The number of the Project controller workers.
    workers: 1
  workspace:
    # -- The number of the Workspace controller workers.
    workers: 1
    # -- The minimum frequency at which watched workspace resources are reconciled. Format: 5s, 1m, etc.
    syncPeriod: 5m

# -- Custom Certificate Authority bundle to validate API TLS certificates. Expects a path to a CRT file containing concatenated certificates.
customCAcertificates: ""

# -- Default agent pool configuration.
defaultAgentPool:
  # -- Whether or not the default agent pool is enabled.
  enabled: false
  # -- The name of the default agent pool.
  name: ""
  # -- The namespace of the default agent pool.
  namespace: ""
  # -- The organization associated with the default agent pool.
  organization: kubernetes-operator
  token:
    # -- Reference to the secret key for the default agent pool token.
    secretKeyRef:
      # -- The name of the secret that contains the default agent pool token.
      name: tfc-operator
      # -- The key within the secret that contains the default agent pool token.
      key: token
  # -- List of agent tokens.
  agentTokens:
    - name: default
  # -- Whether or not the default agent pool is enabled.
  agentDeployment:
    # -- The number of replicas for the agent deployment.
    replicas: 3
    spec:
      containers:
        - name: tfc-agent
          # -- The image for the agent container.
          image: hashicorp/tfc-agent:latest
